[project]
name = "kb-design"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
package = false

[tool.uv.workspace]
members = ["packages/kb-core", "packages/kb-topics", "packages/kb-sources", "packages/kb-vocab", "packages/kb-vocab-shacl", "packages/kb-vocab-ccs", "packages/kb-vocab-writing", "apps/obsidian", "apps/vocab-preview", "apps/vocab-rdf-preview"]

[dependency-groups]
dev = ["kb-core", "kb-topics", "kb-sources", "kb-vocab", "kb-vocab-shacl", "kb-vocab-ccs", "kb-vocab-writing", "kb-obsidian", "kb-vocab-preview", "kb-vocab-rdf-preview"]

[tool.uv.sources]
kb-core = { workspace = true }
kb-topics = { workspace = true }
kb-sources = { workspace = true }
kb-vocab = { workspace = true }
kb-vocab-shacl = { workspace = true }
kb-obsidian = { workspace = true }
kb-vocab-preview = { workspace = true }
kb-vocab-ccs = { workspace = true }
kb-vocab-rdf-preview = { workspace = true }
kb-vocab-writing = { workspace = true }
